feat: Use llm.txt for doc reference. rewrite this pr to include searc… (#21)
* feat: Use llm.txt for doc reference. rewrite this pr to include search doc based on frequency and relevance & fetch doc from uri

* fix: Remove unrelated files

* fix: revert code change in github workflow

* fix: readme naming fix

* fix: remove comment

* fix: refactor some code, optimize some logic

* fix:revert github workflow

diff --git a/.github/workflows/pypi-publish-on-release.yml b/.github/workflows/pypi-publish-on-release.yml
--- a/.github/workflows/pypi-publish-on-release.yml
+++ b/.github/workflows/pypi-publish-on-release.yml
@@ -22,37 +22,37 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
-      with:
-        persist-credentials: false
+      - uses: actions/checkout@v4
+        with:
+          persist-credentials: false
 
-    - name: Set up Python
-      uses: actions/setup-python@v5
-      with:
-        python-version: '3.10'
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.10'
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install hatch twine
-    - name: Validate version
-      run: |
-        version=$(hatch version)
-        if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Valid version format"
-            exit 0
-        else
-            echo "Invalid version format"
-            exit 1
-        fi
-    - name: Build
-      run: |
-        hatch build
-    - name: Store the distribution packages
-      uses: actions/upload-artifact@v4
-      with:
-        name: python-package-distributions
-        path: dist/
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install hatch twine
+      - name: Validate version
+        run: |
+          version=$(hatch version)
+          if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              echo "Valid version format"
+              exit 0
+          else
+              echo "Invalid version format"
+              exit 1
+          fi
+      - name: Build
+        run: |
+          hatch build
+      - name: Store the distribution packages
+        uses: actions/upload-artifact@v4
+        with:
+          name: python-package-distributions
+          path: dist/
 
   deploy:
     name: Upload release to PyPI
@@ -70,10 +70,10 @@ jobs:
       id-token: write
 
     steps:
-    - name: Download all the dists
-      uses: actions/download-artifact@v4
-      with:
-        name: python-package-distributions
-        path: dist/
-    - name: Publish distribution 📦 to PyPI
-      uses: pypa/gh-action-pypi-publish@release/v1
+      - name: Download all the dists
+        uses: actions/download-artifact@v4
+        with:
+          name: python-package-distributions
+          path: dist/
+      - name: Publish distribution 📦 to PyPI
+        uses: pypa/gh-action-pypi-publish@release/v1
